# Project-wide Gradle settings.
android.useAndroidX=true
org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.caching=false
org.gradle.configuration-cache=false
org.gradle.vfs.watch=false
kotlin.code.style=official
android.nonTransitiveRClass=true
kotlin.compiler.execution.strategy=in-process
googleServices.missing.passthrough=true
